language: elixir
env:
  - MIX_ENV=test
elixir:
  - 1.9.0
otp_release:
  - 21.3
script: mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
